version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run:
        name: "Build image"
        command: docker build -t pagerinc/cloud-sdk:${CIRCLE_SHA1:0:8} .
    - run: |
        docker create -v /tmp/test --name test alpine:3.8 /bin/true
        docker cp test/tests.bats test:/tmp/test
        docker cp test/run.sh test:/tmp/test
        docker run -t --volumes-from test pagerinc/cloud-sdk:${CIRCLE_SHA1:0:8} '/tmp/test/run.sh'

  publish:
    machine: true
    steps:
    - checkout
    - run:
        name: Publish Docker Image to Docker Hub
        command: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker build -t pagerinc/cloud-sdk:${CIRCLE_TAG} -t pagerinc/cloud-sdk:latest .
          docker push pagerinc/cloud-sdk:${CIRCLE_TAG}
          docker push pagerinc/cloud-sdk:latest

workflows:
  version: 2
  build-n-publish:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - publish:
        requires:
        - build
        filters:
          tags:
            only: /.*/
          branches:
            ignore: /.*/
